### ISSUE TITLE
Combine with QuantumTomography.jl?

### ISSUE THREAD

**Issue by blakejohnson** [BBN-Q/SchattenNorms.jl#1]
I'm all for small, focused packages, but this seems like you are slicing the pie awfully thin. Can we combine this with QuantumTomography.jl?

**Comment by marcusps** [comment]
The package looks light right now because it does not have any of the diamond norm stuff, but I'm about to push that.

I don't think it is a good idea to combine it with QuantumTomography.jl, as these norms have applications outside quantum information. Moreover, even within quantum info there are many cases where one may want to use the norm without doing anything tomography related.
